# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'albums' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for albums

  target 'albums-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'albumsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'albums-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for albums-tvOS

  # target 'albums-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
